### ISSUE TITLE
Screen is grey / flickering after waking up from sleep [framework]

### ISSUE THREAD

**Issue by realitymolder** [ublue-os/bluefin#1084]
### Describe the bug

Coming back from sleep - the login manager + desktop are getting grey screen.... 
+ another issue, after i somehow passed it the screen flicker like crazy - moving the cursor around and getting some graphical changes will result stability but only in certain graphical changes (?) Videos are attached. 

### What did you expect to happen?

- use the computer
- put it to sleep / close lid
- get back to work on it  

### Output of `rpm-ostree status`

```shell
rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:979d1152ed6eb19346f4cbc971ba7d94777396874f9812824490acdd505f56b6
                  Version: 38.20240401.0 (2024-04-02T16:55:14Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:73af9afc69379eceb74fe7670f5669d3c91704f6da741ad5de5148d0493f4530
                  Version: 38.20240330.0 (2024-03-30T16:51:07Z)
```

### Extra information or context

https://github.com/ublue-os/bluefin/assets/26459151/00e549ef-4eb2-4951-bf7e-6b84f8ffebd1

+ Wanted to add another video but its too large for GH

**Comment by cflewis** [comment]
Is it a Ryzen? It might be https://github.com/FrameworkComputer/linux-docs/blob/main/Fedora40-amd-fw13.md#optional-and-only-if-needed---current-amd-ryzen-7040-series-workarounds-to-common-issues

**Comment by alexcash** [comment]
This is happening for me on the 7640u framework as well. Manifests more like a solid white screen than artifacts per se, but similar to the video. I tried moving to latest/40 to see if that sorted it, but it repros there too. It does sound like the issue @cflewis linked to a workaround for. There's also a bluefin specific post on setting `amdgpu.sg_display=0` on the discourse https://universal-blue.discourse.group/t/bluefin-on-the-framework-13-amd-edition-ryzen-7-7840u/406 though @castrojo replies and references https://github.com/ublue-os/bluefin/issues/998 which is closed. Maybe this specific workaround didn't get ported to bluefin from the framework ublue? 

The latest on the redhat tracker suggests this will be fixed by a framework bios update soon. https://bugzilla.redhat.com/show_bug.cgi?id=2247154#c17

❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:6d78a10b2cb7328ae0d40e592a9ff6084bf585937c956000d949e07c2cd97e9c
                  Version: 40.20240513.0 (2024-05-13T18:03:44Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:d81ba80060fc9f1f59990c3a7ab5a7df6119dad419cb5ce74910f7909f9e99e8
                  Version: 39.20240513.0 (2024-05-13T16:56:33Z)

**Comment by ctsdownloads** [comment]
@alexcash Can I confirm with you, are you on FW 13 AMD (latest BIOS is 3.05) or FW 16 (latest BIOS is 3.03)? Video looks like this could be on FW 16 which the latest BIOS would be lvfs with 3.03.

**Comment by alexcash** [comment]
> Can I confirm with you, are you on FW 13 AMD (latest BIOS is 3.05)

I'm on a framework 13 running JFP30.03.03 BIOS. So you're right, I'm out of date! I'll update and report back.

> Video looks like this could be on FW 16

The video shows a 13 as well. You can tell because the power button/fingerprint reader (glowing square) is on a silver island up by the hinge. The 16 puts that in a black bar next to an up-firing speaker further from the hinge.

**Comment by cflewis** [comment]
So I am getting the white screen when running Aurora. The flickering screen was Gnome but I think the doc from Framework I liked fixed that one. I am beginning to suspect they may be two different issues.

**Comment by ctsdownloads** [comment]
> I'm on a framework 13 running JFP30.03.03 BIOS. So you're right, I'm out of date! I'll update and report back.
> 
> >

Please do, then let us know.





> The video shows a 13 as well. You can tell because the power button/fingerprint reader (glowing square) is on a silver island up by the hinge. The 16 puts that in a black bar next to an up-firing speaker further from the hinge.

Ah, I missed that. I see it now.

**Comment by ctsdownloads** [comment]
> So I am getting the white screen when running Aurora when I full-screen a video application _sometimes_, and a reboot fixes it. Does that sound like what you are seeing @alexcash ? The flickering screen was Gnome but I think the doc from Framework I linked fixed that one. I suspect the blank screen is a separate issue.
> 
> I updated the BIOS yesterday but honestly don't remember if I've seen the bug since then.

Yeah, per AMD, the BIOS update should address it.

**Comment by alexcash** [comment]
> So I am getting the white screen when running Aurora when I full-screen a video application sometimes, and a reboot fixes it. Does that sound like what you are seeing @alexcash ?

Nope, this is always when opening the lid after it's been shut for a few hours. Mostly a white screen with a little bit of flickering. If that's different than what this was filed to track, I apologize for hijacking the thread.

> Please do, then let us know.

Only a day in so knock on wood, but I've not seen the issue since updating BIOS. I apologize for creating noise, this seems like a user error.  I've developed on mac for years but I admit to being a linux nub. Bazzite and now Bluefin have enticed me to try out all kinds of new stuff.

It seems like `dmidecode` has all the info in it you'd need to detect various framework models and the current bios version. One could imagine a script  that tells idiots like me to upgrade, which you could add to `ujust update`. Filed under "I want a pony."

**Comment by ctsdownloads** [comment]
> Only a day in so knock on wood, but I've not seen the issue since updating BIOS. I apologize for creating noise, this seems like a user error. I've developed on mac for years but I admit to being a linux nub. Bazzite and now Bluefin have enticed me to try out all kinds of new stuff.

Okay, cool. Keep us posted.  :)
