### ISSUE TITLE
Apply Framework Laptop headphone audio fix also to Intel based models

### ISSUE THREAD

**Issue by birkenbube** [ublue-os/bluefin#1335]
### Describe the bug

When plugging in headphones into the 3.5mm audio jack of my 11th gen Intel Framework, I get an annoying beeping sound every time the sound chip goes into power saving mode. The built in microphone is recognized correctly. I see this has been addressed for AMD based models in #1259. The fix however seems to apply to both AMD and Intel as mentioned [here](https://community.frame.work/t/resolved-framework-13-amd-headphone-jack-buzz-when-not-playing-audio/39116/8).

### What did you expect to happen?

The sound fixes should also be applied for 11th gen (and possibly other?) Intel based Frameworks. 

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:latest
                   Digest: sha256:3aa6adae2e25fcb950ccd4a9a43deca4c59430fdbb10ac3cc559cf811f641462
                  Version: 40.20240520.0 (2024-05-20T22:02:50Z)
                     Diff: 14 upgraded, 8 added
          LayeredPackages: yakuake

● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:latest
                   Digest: sha256:0c219e921dabb6364178b757e735c2dfb3d1bd924c0ebd4dfa5d7d05348ab69d
                  Version: 40.20240518.0 (2024-05-20T16:52:47Z)
          LayeredPackages: yakuake

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:latest
                   Digest: sha256:3407877930171766c91a4120f5b166745e199cbdf20b6c7073137b04276a2fb6
                  Version: 40.20240518.0 (2024-05-19T01:40:27Z)
          LayeredPackages: yakuake

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:latest
                   Digest: sha256:c840fc5597945bba3184927b76721702a0edebcc92d2a166ece4740dbac25000
                  Version: 40.20240504.0 (2024-05-04T16:52:03Z)
          LayeredPackages: yakuake
                   Pinned: yes

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:39
                   Digest: sha256:5dce4605b0a062c15aa0def7c7d95a4f032a44dfae61ce423d56f9b07359e658
                  Version: 39.20240422.0 (2024-04-23T02:04:38Z)
                   Pinned: yes
```

### Output of `groups`

```shell
jan wheel lxd incus-admin libvirt docker
```

### Extra information or context

As the microphone is recognized, I suspect `sudo tee /etc/modprobe.d/alsa.conf <<< "options snd-hda-intel index=1,0 model=auto,dell-headset-multi"` might not be needed on Intel, not sure.

**Comment by ctsdownloads** [comment]
Hi @birkenbube,

It's Matt from Framework. 11th and 12th gen are subject to this: https://frame.work/blog/solving-for-silicon-shortages
Which leads us to the issues we have with Tempo and what led us to addressing this head on with our own separate audio expansion card (which is superior in every possible way).

As noted on the recently updated https://frame.work/linux page, we're hyper focused on Bluefin compatibility with 13th gen, and AMD offerings due to available cycles I have available. With time, I will be doing additional testing on the legacy boards as well.

As for model=auto,dell-headset-multi", this is likely a legacy holdover since resolved and no longer needing this workaround. If you have verified it's not needed any longer, we can have model=auto,dell-headset-multi removed. 

But in all truth, we [highly recommend this card](https://frame.work/products/audio-expansion-card) for those on 11th gen who want decent sound without the Tempo headaches.

That said, and not something I have cycles to test right now.

/sys/module/snd_hda_intel/parameters/power_save with a echo 0.

Folks have reportedly created a systemd service to address this as as one shot on boot. Hacky, but would likely help.

Best path forward, get the Framework audio expansion card. Every single person I have that has done this has been shocked at how much better it is.

**Comment by birkenbube** [comment]
Hi @ctsdownloads, thanks for your detailed answer. I completely understand that focusing on the newer models is a priority right now. I mostly use wired headphones as an emergency backup for my Bluetooth ones anyway, but I will definitely check out the expansion module you mentioned.

As for the parameters, I did try booting up with the kernel boot parameter `snd_hda_intel.power_save=0` as suggested [here](https://community.frame.work/t/resolved-framework-13-amd-headphone-jack-buzz-when-not-playing-audio/39116/8) and that seems to fix the beeping sound. The headset microphone also works.
