### ISSUE TITLE
Add shell integration to `ujust bluefin-cli`

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1336]
`ujust bluefin-cli` installs all the tools we need for the CLI, but we still need to integrate the configs so that I can "turn it on" and then all the shell/aliases are set up automatically.

https://github.com/ublue-os/toolboxes/tree/main/toolboxes/bluefin-cli/files/etc

This may make more sense in config so that bazzite can have it and can make their own choices, not sure where things live now, hah.

**Comment by geoffreysmith** [comment]
I can take this on but the whole thing is a mess, and I don't really know what the "roadmap" for this is. It seems like everything eventually ends up as a quadlet, I'm already having issues with things like invokeai using the same port as cockpit. I did not realize people use quadlets for production systems or anything more than local testing.

After my last comment I took a deep dive into podman/ostree/distrobox/etc because my previous workflow involved not having the host OS be Linux, so the mental model of sandboxing was different. Why not use k8s workflow as you're essentially building separate apps without replica sets, etc. Then you can use cuelang for schema validation and programmatically create all these then test the schema.

You're more knowledgeable than I am on this but if you treat bluefin-cli as just another app in a cluster unless I'm missing something it makes it a lot easier. I have some issues with it being not hardened but that's your call, the fact it looks different from distroboes, apps, etc. that all run under systemd is super confusing at least to me unless you take a deep dive. Not to mention there's a ton of logic in bash files even though you can use golang/python to create these easily.

Sorry if this sounds critical it isn't, I just don't know if these are intentional design decisions or just organic. Because you have a brewfile in one repo creating systemd units in another and in that same repo it creates other things. I abstracted this a bit and treated everything as a separate pod in a k8s cluster and it became a lot easier to manage. But I don't know if there's huge gaps I'm missing? It sounds more complex but after realizing people were using  quads for prod and not just to play around in it kinda made sense. I have no idea how the different bluefin variations users do things but I'd wager to guess its probably mostly in the -dx mode or using it for gaming.

**Comment by castrojo** [comment]
This issue is for integrating the UX from the bluefin-cli container onto the host with brew. 

But I think your question is, why we have it this way? If so basically we use quadlets to manage the lifecycle of the distroboxes we include, which means creating, destroying, updating, etc. They're designed to be throw away cattle boxes, and not pet containers like a manually made distrobox, so we just have quadlets do it automatically. 

> Because you have a brewfile in one repo creating systemd units in another and in that same repo it creates other things.

Where's this happening exactly? Maybe I can explain what's happening lol, a bunch of this is indeed organic.

**Comment by kragil** [comment]
Why not start with some basic bash aliases for most of the CLI tools .. you have to start somewhere and something is better than nothing, right?

**Comment by castrojo** [comment]
Yeah, we have that already, see the link in my first post, we just need to
copy that over to the host.

**Comment by nreith** [comment]
What would it take if one wanted the bluefin-cli experience with all the bells and whistles, but not wolfi? Say Ubuntu, Debian, or Fedora?

**Comment by castrojo** [comment]
Grab the package list (or Brewfile) and then just build it with any one of those. Boxkit is designed for builting your own toolboxes: https://github.com/ublue-os/boxkit

Though these days we ship bluefin-cli as brew packages on the host: https://github.com/ublue-os/bluefin/blob/main/system_files/shared/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
