### ISSUE TITLE
Update Failed: signature when validating ASN.1 encoded signature

### ISSUE THREAD

**Issue by Malix-off** [ublue-os/bluefin#1484]
### Describe the bug

```fish
malix@malix-pc /u/s/ublue-os> rpm-ostree update
note: automatic updates (stage) are enabled
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:stable
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: cryptographic signature verification failed: invalid signature when validating ASN.1 encoded signature
```

### What did you expect to happen?

Working Updates

### Output of `rpm-ostree status`

```shell
malix@malix-pc /u/s/ublue-os [1]> rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.service: last run failed
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:stable
                   Digest: sha256:3a86261872d8d7d67c9b6cd494c57c186d9bc27626aeaa978a954babd70be2ed
                  Version: 40.20240702.0 (2024-07-02T05:58:47Z)
          LayeredPackages: google-chrome-stable

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:3d8bcf55e734ae743249eb7c0cf8c15494041bd7f97432d1d2ee9c9ee36d040c
                  Version: 40.20240630.0 (2024-06-30T18:52:33Z)
          LayeredPackages: google-chrome-stable
```

### Output of `groups`

```shell
`malix wheel docker incus-admin lxd libvirt`
```

### Extra information or context

1. I used `rpm-ostree rebase ...:stable` after the recent 3.0.0 update
2. I tried to repair the automatic update functioning (see https://github.com/ublue-os/config/issues/286)

**Comment by p5** [comment]
We made some mistakes yesterday which caused updates to break.
Please can you follow the instructions in [this Discourse post](https://universal-blue.discourse.group/t/important-announcement-regarding-system-updates-action-needed/2689) to remediate the issues.

TL;DR
We lost access to our signing keys so had to rotate them.
Users need to run the following command or manually perform the actions in [this script](https://github.com/ublue-os/config/blob/5c4144d38a2a61e44ca704ffdf2d50bbcb9ff7ed/scripts/fix-key-and-update.sh)

```
$ curl -sL https://fix.universal-blue.org/ | sudo bash 
```

Apologies for the inconvenience caused by this!

**Comment by castrojo** [comment]
https://universal-blue.discourse.group/t/important-announcement-regarding-system-updates-action-needed/2689

Placeholding this here. ^
