### ISSUE TITLE
InputLeap does not start server.

### ISSUE THREAD

**Issue by TeamLinux01** [ublue-os/bluefin#1520]
### Describe the bug

When I open InputLeap on Aurora-DX, I get a message saying:
```
You are using wayland session, which is currently not fully supported by InputLeap.
```

I click `OK` and then click `Start` with `Server` checked and `Configure interactively:` selected. It does not start and the log constantly prints
```
[2024-07-19T22:08:56] INFO: starting server
[2024-07-19T22:08:56] INFO: config file: /tmp/InputLeap.LnTPYX
[2024-07-19T22:08:56] INFO: log level: INFO
[2024-07-19T22:08:56] FATAL: An error occurred: Missing libportal InputCapture portal support
[2024-07-19T22:08:56] ERROR: process exited with error code: 1
[2024-07-19T22:08:56] INFO: detected process not running, auto restarting
```
with `/tmp/InpuxLeap.random` being different each time.

### What did you expect to happen?

I think the program is suppose to open the wayland InputCapture portal so I can select what to share, but I am not sure. I do expect the server to start and accept connections.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 9h ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:stable
                   Digest: sha256:8655fb2ac0507fc11212b094f91889414463e67e1b90adecfc83e24ab1a86d20
                  Version: 40.20240715.0 (2024-07-15T12:11:25Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:stable
                   Digest: sha256:778550966d6e3c9b7f8a71cfe3f26ea487a104e8f38e9ecb9e8772b481bf9aa5
                  Version: 40.20240714.0 (2024-07-15T00:43:18Z)
```

### Output of `groups`

```shell
daniel wheel wireshark incus-admin lxd docker libvirt
```

**Comment by Rayvert64** [comment]
I have this same issue, but my system crashes after trying to stop the server. 

I am guessing there's a package missing? I think on arch you have to have the `libinput-inputcapture` package included, but I can't seem to find it for us. Perhaps it got renamed or is part of some other package now?

**Comment by Rayvert64** [comment]
> I have this same issue, but my system crashes after trying to stop the server.
> 
> I am guessing there's a package missing? I think on arch you have to have the `libportal-inputcapture` package included, but I can't seem to find it for us. Perhaps it got renamed or is part of some other package now?

After looking at the aur, this just looks like a custom build of libportal? 
https://aur.archlinux.org/packages/libportal-inputcapture

**Comment by Rayvert64** [comment]
More info on work being done:
https://discussion.fedoraproject.org/t/input-leap-fedora-39-gnome-wayland/95856/8

**Comment by Rayvert64** [comment]
## I have a workaround that works well while we wait for a real update to `libportal` that doesn't mess with your aurora/bluefin/silverblue install

Turns out you can install `libinput` and `input-leap` from a container built with`distrobox`. But not only that, you can actually RUN `input-leap` from the container and it will work for both the server AND the client! (WAWAWEEWA!)

If you want, just follow the instructions bellow! We are basically gonna compile everything we need... and desire!

### First make a distrobox container based on the fedora 40(I used `fedora-toolbox-40`)
First I just ran this:
```bash
sudo dnf group install "C Development Tools and Libraries" "Development Tools"
```
I usually wouldn't run this on a development machine, but since it's a container I kind of don't care. (Tell me if I should!)

Then install the rest of the dependencies:
```bash
sudo dnf install libportal-devel libei-devel libSM-devel libICE-devel avahi-compat-libdns_sd-devel libcurl-devel "qt6*-devel" gtk3-devel gtk4-devel vala gobject-introspection-devel glib2-devel glibc-devel libglibutil meson gcc cmake make llvm pip3
```

### Now compile and install the code from the two git repos we need this is mostly taken from my last comment
To do this simply follow these nifty steps(from: https://discussion.fedoraproject.org/t/input-leap-fedora-39-gnome-wayland/95856/9):
1. `libportal`'s InputCapture portal stuff was merged but has not yet been release, so we need to clone and build the latest libportal.
First set yourself up a nice dev directory or something and `cd` in there. 
In the original example you'll see `shymega` uses `~/Developer` as he(or she!) enjoys the more distinguished things in life.
```bash
git clone git@github.com:flatpak/libportal.git
```
```bash
cd libportal
```
Usually we wouldn't want to `sudo pip install` anything, but if you got all the way here, I assume you are cool and awesome and therefore don't care for such nitpickery. (But seriously though, use virtenv when possible or whatever other python dev env on serious installs)
```bash 
sudo pip install jinja2 pygments typogrify
```
```bash
meson _build
```
```bash
ninja -C _build
``` 
```bash
cd _build
```
```bash 
sudo meson install
```
2. Then we'll need to get the latest input-leap sources 
Before the next command, go back to the root of your dev folder. Although... I guess it might still work in the `_build` directory?... Feel free to try that if you are looking for a spicy experience!
```bash 
git clone git@github.com:input-leap/input-leap &&  cd input-leap
```
```bash 
git submodule update --init --recursive
```
This next step turns on libei support, it's an important feature as we all know!
```bash
sed -ir 's/INPUTLEAP_BUILD_LIBEI\(.*\)OFF/INPUTLEAP_BUILD_LIBEI\1ON/' CMakeLists.txt 
```
4. Now we can build and install input-leap in the fedora container
```bash
./clean_build.sh
``` 
```bash
sudo cmake --install build
```

## Now for the moment you have all been waiting for!
Run this while still within the container:
```bash
input-leap
```

It should just work!

**Disclaimer: I totally was going to try and possibly mess up my actual install and just install the libraries on my bluefin install. I only noticed afterwards that I had installed the libraries and the programs in my container and that it was somehow working... Feel free to judge, if it's not prod I tend to just yolo things.**

**Comment by RaduAvramescu** [comment]
Thanks for the instructions! @Rayvert64

I've tried them out on the `bazzite-gnome` image and can say that they ended up working for me. I omitted running the command you said doesn't work: `sudo cmake --install build`

That said, I do have a couple of notes:
1. I think it would be good to provide the command others could use to create the distrobox container. In my case, I used `distrobox-create --name fedora-toolbox-40 --image fedora-toolbox:40`
1. `pip3` does not exist as a package in my case - I believe this should be `python3-pip`
2. `git clone git@github.com:flatpak/libportal.git` - this doesn't really work for me by default because I believe this is the clone URL if using ssh, the https one should always work
3. `git clone git@github.com:input-leap/input-leap` - same as #2 from above

**Comment by RaduAvramescu** [comment]
There's a new update for both input-leap and libportal here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-1ae7da3374

I no longer need to follow all the instructions above, on Bazzite. I'll list updated instructions below.

Create the initial container:
```
distrobox-create --name fedora-toolbox-40 --image fedora-toolbox:40
```

Enter the container:
```
distrobox enter --name fedora-toolbox-40
```

Update the packages:
```
sudo dnf upgrade --refresh
```

Install input-leap:
```
sudo dnf install input-leap
```

Export the app to the host system:
```
distrobox-export --app input-leap
```

That is all. Now `Input Leap` should appear on the host system, in the applications list.

Presumably, this should not even be necessary on images that already come with `input-leap` preinstalled, as they should be fetching the update soon.
