### ISSUE TITLE
k8s-dev-tools recipe missing

### ISSUE THREAD

**Issue by SelfhostedPro** [ublue-os/bluefin#1692]
### Describe the bug

When running `ujust k8s-dev-tools` I get the following error:
```
error: Justfile does not contain recipe `k8s-dev-tools`.
```
I also don't see it in the repo but the docs reference it [here](https://docs.projectbluefin.io/bluefin-dx#kubernetes-and-other-cloud-native-tooling)

### What did you expect to happen?

To have some kubernetes tools installed in the recommended fashion.

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:stable
                   Digest: sha256:f989c0c361a3af512c7db9c4af593e55147b8f3d4e0768b34e9ef001a1fb6ede
                  Version: 40.20240917.0 (2024-09-18T21:13:58Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:gts
                   Digest: sha256:2a062f1c9cf00415456d9180c1bf080ac4293b8f6a4cc7d7c29ad669ffc6c49e
                  Version: 39.20240914.0 (2024-09-15T05:54:19Z)
```
```


### Output of `groups`

```shell
groups
none wheel
```

### Extra information or context

Pretty fresh bluefin-dev install.

**Comment by castrojo** [comment]
This fix should be in the next build tomorrow night.

**Comment by castrojo** [comment]
This is still missing on the image, need to investigate why.

**Comment by Yunraze** [comment]
Hey, I suggested some tools for this recipe earlier. I was wondering why it still doesn't work and did some digging:

- https://github.com/ublue-os/config/blob/main/build/ublue-os-just/06-k8s-dev-tools.just exists but doesn't seem to be referenced in https://github.com/ublue-os/config/blob/main/build/ublue-os-just/ublue-os-just.spec at all. Is this deliberate or an omission?
- 06-k8s-dev-tools.just also references https://github.com/ublue-os/config/blob/5fa00015f4ea1b2d6c0f7d66fb2e67c4daa74109/build/ublue-os-just/06-k8s-dev-tools.just#L7C5-L7C72 to be /usr/share/ublue-os/homebrew/kubernetes.Brewfile but the path to that file inside /files is is /usr/ublue-os/homebrew/kubernetes.Brewfile.

I'm not sure if I'm completely off, so just adding a comment instead of trying to do a PR.
