### ISSUE TITLE
GNOME Software prompts to enable third party repos

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#175]
On fresh install when you first launch gnome-software you get this:

![image](https://user-images.githubusercontent.com/1264109/232233815-e2a9da86-1399-4ad5-9d1c-4a39b69c812c.png)

This is confusing because we set everything up already, so we need to find a way to disable this dialog. bigpod thinks it might be a dconf key.

**Comment by castrojo** [comment]
Perhaps setting /org/gnome/software/first-run to false?

**Comment by castrojo** [comment]
This is still happening so leaving it open, though the setting seems benign.

**Comment by bobslept** [comment]
This seems to be triggered by the existence of a state file located in `/var/lib/fedora-third-party/state`

The file is created with the `fedora-third-party` command which is actually run by yafti. The problem here is that it never succeeds because it hasn't enough rights to create this file. 

Running it as a user will result in:
```
[user@fedora ~]$ fedora-third-party disable
fedora-third-party must be run as root.
[user@fedora ~]$ 
```

Another thing is that if `gnome-software` is launched (for example background) before the command actually did run with enough rights you will still see the the popup. If you first do a `gnome-software --quit` and then launch it again you don't see the popup.

**Comment by bobslept** [comment]
I think since we introduced the flatpak-manager we no longer have these prompts, because we disable the third party repos there also. And those run with higher permissions then before.

https://github.com/ublue-os/bluefin/blob/fe75d1d74fb593dbb0430a3be38d9d292ec31eb0/usr/bin/ublue-system-flatpak-manager#L39-L40

Tested on a clean installation with  `bluefin-38-2023-10-27-x86_64-rc.iso` and don't see the prompts anymore.

Therefore I think this issue can be closed.
