### ISSUE TITLE
Define bluefin release stream structure

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1941]
We should start talking about this. Leaving out stable-daily it's:

gts: Fedora 40
stable: CoreOS Stable
beta: CoreOS Testing
latest: Fedora 41

How about: 

gts: Fedora 40
stable: CoreOS Stable
testing: CoreOS Testing
latest: Fedora 41
beta: whatever, probably fedora's next release, undefined and YOLO if you opt in

I don't think we need to bring CoreOS `next` over. But, I'd also like to talk about making testing be where we land Bluefin changes that need a shakedown. Then we can maybe do a thing where we can use a bot or something to selectively merge features from testing to gts/stable. Don't make me use the git cli pls lol.

**Comment by tulilirockz** [comment]
The beta thing seems really really useful to ship/test new features and integration w/ the freshest stuff but wasnt that the purpose of `:latest`?

**Comment by castrojo** [comment]
I think by now `latest` just should be vanilla current version of Fedora. There will be people who want that but don't want to be beta testers of bluefin features. And if you see `testing` you know you're going to be a guinea pig, where as `latest` doesn't explain that. 

As for the rawhide thing that's never been tenable for us for practical reasons, that's the distro's test channel anyway, not ours. We're kind of only interested in the final thing they publish.

**Comment by tulilirockz** [comment]
Sounds pretty nice! Testing seems like a really nice name for that! - I also propose we should try using separate branches for each stream, kinda like [nixpkgs](https://github.com/NixOS/nixpkgs) does. It would be a stream like `testing -> latest -> stable -> gts` or something like that, that would allow us to have stream-specific fixes for temporary things, and would make it so recently merged changes dont affect the other branches straight away (then we dont need to wait till the `:stable`/`:gts` tags are built until we can merge a PR)

**Comment by m2Giles** [comment]
GTS - Fedora -1 w/ gated kernel + zfs
Stable - CoreOS version w/ gated kernel + zfs

Latest - Fedora Current, current kernel, no zfs. Since we have a latest tag, this I think is the least surprise and is the closest to upstream Fedora. While you will experience bugs, this is most of the time due to Fedora current version. If anything this could be where coreos-testing exists if we want to make that a more permanent thing.

Beta - this is for testing. While right now it's being used as a smoke test by following coreOS testing, it really should be thought of our one tag that is for playing around.

We are already offering a lot of dials between GTS, stable, stable-daily, and latest.

Like having beta on coreOS testing around the bump for stable was nice to be able to test it out. Before latest bumped again being able to preview and see that ISO builds would be broken was nice. Beta to me is that playground tool.

**Comment by castrojo** [comment]
Also let's give this one a few days so we can get input from others.

**Comment by tulilirockz** [comment]
+1 for M2's proposal too!

**Comment by donalus** [comment]
If fresh eyes are helpful here, then I think that M2's proposal is clearer that the current hierarchy.
