### ISSUE TITLE
Split aurora/bluefin repos

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1989]
It's becoming untenable to deal with the aurora/bluefin issues in the same repo, let's split it out or move aurora out of the org.

**Comment by tulilirockz** [comment]
I suppose this also means no "Bluefin but its COSMIC" in the future or whatever else right?

**Comment by tulilirockz** [comment]
I feel like separating them won't do too much good, Bluefin and Aurora are just so similar that there would be a ton of duplicate issues on the aurora/bluefin repos... To be honest this probably would be good tho since it would make Bluefin more focused on the GNOME experience and would make the repo slimmer...

**Comment by castrojo** [comment]
> I suppose this also means no "Bluefin but its COSMIC" in the future or whatever else right?

Nope, our scope is already defined, Cosmicfin is for someone else to make.

**Comment by RealVishy** [comment]
> I feel like separating them won't do too much good, Bluefin and Aurora are just so similar that there would be a ton of duplicate issues on the aurora/bluefin repos... To be honest this probably would be good tho since it would make Bluefin more focused on the GNOME experience and would make the repo slimmer...

I don't mind the repos splitting and/or Bluefin/Aurora going for more opinionated desktop decisions but I'm worried about divergence in the goals of each desktop.

Are Bluefin and Aurora built with the same goals in mind but GNOME/KDE as the differentiator or is there going to be more to split them later?

**Comment by castrojo** [comment]
Example from today, since none of the bluefin maintainers use aurora it's difficult for us to help with issues like this one:

https://github.com/ublue-os/bluefin/issues/2001

And then the sddm crashers people complain about in discord, etc. I can't speak for the others but I don't have the time allotment for another desktop. We picked GNOME because of our experience with it, I can't effectively anything else, so I think it should be split so that people can focus on what's important to them. And then someone else can take lead on adding the SDDM service you wanted etc in a separate repo. We'd need new people to step up to keep it going though.

**Comment by bsherman** [comment]
I think there's a few good reasons to split Bluefin and Aurora into distinct repos.

First is just the branding. It's confusing that Aurora is not Bluefin but is build with Bluefin. Bug reports/issues/PRs are all done in the bluefin repo, etc. It creates the belief that Aurora must be in lockstep with Bluefin, but that's quite clearly not the case. And it's just messy trying to keep track of that stuff in one repo.

Second is the technical challenges of keeping distinct products built in the same code base. While not insurmountable, clearly it's being done now, it is a burden on maintainers. Sometimes it's hard to know if a change meant for Bluefin will negatively impact Aurora and vice versa, especially they aren't used by the same maintainers. In the case of Bazzite, at least it's ALL Bazzite, just different flavors, so there is an incentive to keep all that together... but Bluefin and Aurora are not the same, so holding them together feels like a tech challenge with no value to make it worthwhile.

I think splitting now would give both products a good start with a solid baseline of build code, but also allow significant simplification to the respective repos. Hopefully this would increase confidence for potential contributors to one or the other, and the maintainers, knowing any submitted changes can't hurt the other project.

**Comment by tulilirockz** [comment]
How would we get to doing that tho? Creating a new repo somewhere w/ the aurora code, then PRing this one to remove all the aurora stuff?

**Comment by noelmiller** [comment]
I think the main thing that concerned me is when we started diverging Aurora and Bluefin in weird ways. Like, keeping the branding separate made some amount of sense due to built in audiences, but not building GTS for Aurora and only latest was a bit odd. I understand wanting to manage less images, but that is one example that it's not Bluefin KDE, it's its own thing. 

I'm OK with whatever the maintainers decide to do, I don't personally use Bluefin or Aurora since a custom Bazzite image serves all of my needs. And it is becoming easier than ever to create your own KDE based image, I don't think all decisions in Bluefin must be taken as gospel on a KDE based image.

**Comment by RealVishy** [comment]
> I think the main thing that concerned me is when we started diverging Aurora and Bluefin in weird ways. Like, keeping the branding separate made some amount of sense due to built in audiences, but not building GTS for Aurora and only latest was a bit odd. I understand wanting to manage less images, but that is one example that it's not Bluefin KDE, it's its own thing.
> 
> I'm OK with whatever the maintainers decide to do, I don't personally use Bluefin or Aurora since a custom Bazzite image serves all of my needs. And it is becoming easier than ever to create your own KDE based image, I don't think all decisions in Bluefin must be taken as gospel on a KDE based image.

AFAIK, GTS doesn't really make sense for KDE because each new feature release often fixes numerous bugs, and KDE still doesn't align perfectly with the Fedora release schedule like GNOME. I think pinning images is a suitable alternative for aurora. 

> I think splitting now would give both products a good start with a solid baseline of build code, but also allow significant simplification to the respective repos. Hopefully this would increase confidence for potential contributors to one or the other, and the maintainers, knowing any submitted changes can't hurt the other project.

Fair enough, one immediate benefit I can see is being able to remove all the gnome-specific `ujusts' on aurora to limit confusion if we split the repos

**Comment by castrojo** [comment]
Ok [ublue-os/aurora](https://github.com/ublue-os/aurora) is set up now. I made a copy of the bluefin repo so it has all the history, and then I turned off all the bluefin builds. I adjusted the permissions to the packages so that the aurora repo can push to it. I can confirm that that's working. 

Currently there's nvidia skew so things are red all over, I am rebuilding kernel-cache/akmods/main now to see if we can make things green again. But worst case we wait for it to resolve itself. I've turned off the aurora builds in bluefin also, so each repo is pushing the correct packages now. 

Now each repo can just cleanup their stuff independently. @NiHaiden check your inbox for repo permissions, and I've also made an Aurora section on the website: https://universal-blue.discourse.group/c/aurora/11

I'll work on moving the issues over as things turn green.

**Comment by castrojo** [comment]
OK ISO secrets updated as well, as the kids say "EZ bro". Please open issues in the appropriate repo if you find stuff!

**Comment by etvt** [comment]
> I made a copy of the bluefin repo so it has all the history

The new [aurora](https://github.com/ublue-os/aurora/commits/main/) repo is missing some commits that happened on [bluefin](https://github.com/ublue-os/bluefin/commits/main/) after the 25th of November. So it seems to me that the copy was made from an older version of bluefin.  
Was this intentional?

(I realized and started investigating because the google font packages were removed after I updated to the latest `aurora-dx:stable-daily`. Not saying I need them, just wanted to see what happened... 😄)

**Comment by castrojo** [comment]
Ah nuts, you're right, I didn't update my local branch before doing the copy. We need this one at least:

- https://github.com/ublue-os/bluefin/pull/2006

**Comment by bsherman** [comment]
I'm working on correcting the missing commits in aurora... please stand by.

**Comment by bsherman** [comment]
Should be fixed up now.
