### ISSUE TITLE
Ship homebrew config out of the box

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#252]
I'd like to ship a working homebrew config for -dx so people who know homebrew can just use it. Installing it works and I was able to install some small tools but we may need to adjust the prefix, when running `homebrew doctor`.

```
Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
```

Detailed instructions: https://docs.brew.sh/Homebrew-on-Linux

**Comment by castrojo** [comment]
All the deps you need are on the -dx image now(ish).

**Comment by marcoceppi** [comment]
Some notes for this. An upstream change is needed for homebrew in the bin/brew script. It finds _where_ homebrew is installed by checking where the current bin/brew script is running - that's typically a symlink to `/home/linuxbrew/.linuxbrew/Homebrew/bin/brew` (where the file is in `/home/linuxbrew/.linuxbrew/bin/brew`. Since `/home` on silverblue (and by extension almost all ublue images) is symlinked to /var/home it resolves the HOMEBREW_CELLAR, HOMEBREW_PREFIX, etc to /var/home/linuxbrew/.linuxbrew which homebrew detects is not /home/linuxbrew/.linuxbrew (though, it reality it is) and causes homebrew to re-compile all formulas instead of pouring from the pre-compiled bottles. To get around this, there are a few strategic areas in the `bin/brew` where checking if we're on linux and that /home is a symlink to the HOMEBREW_REPOSITORY path it's calculated to swap to that expected default path. If a patch for upstream can't be accepted we may need to ship our own bin/brew shim in a place that takes precendence over the one from homebrew in path, with ours short-circuiting what bin/brew does and then sources the Hombrew/brew.sh which is the actual command runner

**Comment by osalbahr** [comment]
Related: [brew on symlinked home #1282](https://github.com/orgs/Homebrew/discussions/1282)

**Comment by osalbahr** [comment]
I’ll see what I can do. Can I be added as an assignee?

**Comment by osalbahr** [comment]
> All the deps you need are on the -dx image now(ish).

What are “deps” here?

**Comment by castrojo** [comment]
https://github.com/ublue-os/bluefin/pull/261/files

**Comment by osalbahr** [comment]
> https://github.com/ublue-os/bluefin/pull/261/files

Oh, are you adding the packages in `groupinstall 'Development Tools'` and `procps-ng curl file git`? That would be nice because then all packages that Homebrew thinks should be installed from source should theoretically all successfully do so (well, if `gcc` works #\<insert-issue-tracker>). But I don't think we need anything past what's already in Fedora to get `brew` to work for end user operations (`brew install <>` pulls bottles aka precompiled binaries).

So far it doesn't seem that a `bin/brew` shim would suffice but I'd need to dig deeper into how `brew install <>` works. I think we should convince `brew install <>` that it is installing in `/home/linuxbrew/.linuxbrew` (because it actually is).

What are your thoughts on just mounting `/home` and have it be the same as `/var/home` (just like in a distrobox but in the host tpp)? I don't know why `/home` is a symlink in Silverblue from the first place tbh.

**Comment by osalbahr** [comment]
FYI see Homebrew/install#786 for a related discussion.

**Comment by osalbahr** [comment]
Hello, me and @rohanssrao wrote a patch in osalbahr/brew#3. Would appreciate testing before I PR to Homebrew.

**Comment by rohanssrao** [comment]
As far as we can tell, `brew developer on` is only needed now because it prevents brew from reverting the sed command by resetting the working directory to mirror master. If the script patch gets merged to Homebrew master, the developer command won't be needed.
In summary, the required change is the removal of two characters (`-P`) from bin/brew.

**Comment by osalbahr** [comment]
Hello, I believe this issue has been fixed upstream:
- Homebrew/brew#15656

**Comment by osalbahr** [comment]
Hello, I believe this issue has been fixed upstream:
- Homebrew/brew#15656

To test the fix, you can run `cd $(brew --repo) && git checkout master && brew update` (as per https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request). I think only running `brew developer on` might also be sufficient.

**Comment by osalbahr** [comment]
@marcoceppi @castrojo I believe the patch is now in the upstream as part of https://github.com/Homebrew/brew/compare/4.0.28...4.1.0, so this issue can now be closed as resolved:

> Feature: support symlinked /home by @osalbahr in https://github.com/Homebrew/brew/pull/15656

https://github.com/Homebrew/brew/releases/tag/4.1.0

> The default Linux installation location (/home/linuxbrew/.linuxbrew) works as expected on Fedora Silverblue and other configurations where /home is symlinked elsewhere.

https://brew.sh/2023/07/20/homebrew-4.1.0/

---

Special thx to @rohanssrao for helping out with testing and keeping my sanity with seemingly inconsistent results.

**Comment by castrojo** [comment]
Sorry for the noise but I just wanted to let you all know that I love this feature so much, thanks for implementing it!
