### ISSUE TITLE
Super-e shortcut isn't working

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#4]
https://github.com/ublue-os/ubuntu/blob/5bf11e901bc64e8c73c46fb7227339d9027534b5/etc/dconf/db/local.d/01-ublue#L62

This should bind super-e to home, but it's not working.

**Comment by ironman820** [comment]
I installed `dconf-cli` in an Ubuntu distrobox, and ran `dconf dump /org/gnome/settings-daemon/plugins/media-keys/` and was sent this output (my key-binding is modeled after my setup in Pop OS!, hence the '\<Super>**f**' instead of **e**):

```
[/]
home=['<Super>f']
```

It appears that this particular key is expecting a list instead of just a string with the keybinding. I'm working on a fresh fork after playing around with ublue-os/ubuntu last week, so I can test a push and see if it updates on the fresh fork before issuing a full PR if you don't get to test it first.
