### ISSUE TITLE
Move to charm.sh rpm repo

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#661]
https://repo.charm.sh/

This exists so we should use it instead of inlining everything. We need to move glow, gum, and add vhs back.

**Comment by hisergiorojas** [comment]
I would like to help but I'm a beginner when it comes to developing a Linux distro.

**Comment by bobslept** [comment]
> I would like to help but I'm a beginner when it comes to developing a Linux distro.

You can follow along with the changes made in the PR above. In short:

- I added a repo file in `dx/etc/yum.repos.d/charm.repo` that we can use with `rpm-ostree install`
- Added the `glow` and `gum` packages to their corresponding bluefin-dx section in the `packages.json` so they get installed via the added repository.
- Removed old way of installing `glow` and `gum` here https://github.com/ublue-os/bluefin/pull/664/files#diff-5fcdf9b4580789697d834d1456a22bcfaa236d668fc180cad4775afc36ed5914L149-L154
- And at last the repo we added, we remove it from the image because the tools are installed and not needed on the end image.

If you have any questions, just let me know!
