### ISSUE TITLE
Ship terminal themes via Gogh 

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#666]
We must have this!!

https://github.com/Gogh-Co/Gogh?tab=readme-ov-file#-terminals

And then let's ship Catppuccin Mocha and Latte for dark/light mode as a default.  Then people can just PR the themes they actually use so we don't overload the menu.

**Comment by rothgar** [comment]
I was looking at these themes and some of them are cool but I don't think they install in the correct folder.

Based on https://github.com/Gogh-Co/Gogh/issues/381 it should be supported but maybe because it's flatpak we need to symlink the themes folder somewhere.

My themes folder is ~/.var/app/com.raggesilver.BlackBox/data/blackbox/schemes

**Comment by castrojo** [comment]
https://github.com/catppuccin/blackbox

Ok I just copied the 4 .json files into that directory and then they show up in the terminal. I think if we do it as part of the first login/yafti step and copy the files there and set the dconf setting that might work!

**Comment by castrojo** [comment]
Prompt comes with so many themes that we don't need to do this.
