### ISSUE TITLE
Track homebrew's state inside bluefin-cli

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#768]
It'd be nice to destroy and assemble the bluefin-cli container without losing all the packages I've installed inside. Jeefy has an idea on how to do this.

**Comment by jeefy** [comment]
**We CANNOT use $USER and must use explicit naming. For this, it's `jeefy` and we're using wolfi distrobox**

- On first boot we make a folder named `/home/jeefy/.homebrew`  
- On first boot we create a file (`/etc/homebrew/brew.env`) upon first-boot that contains the following:
```
HOMEBREW_PREFIX=/home/jeefy/.homebrew
HOMEBREW_REPOSITORY=/home/jeefy/.homebrew
```

From then on, any `brew` command will reference/install/use the mounted user's home directory. Example output after doing that and running `brew install go`

```
📦[jeefy@bluefin ~]$ brew config
HOMEBREW_VERSION: >=4.1.0 (shallow or no git repository)
...
HOMEBREW_PREFIX: /home/jeefy/.homebrew
HOMEBREW_REPOSITORY: /home/jeefy/.homebrew
HOMEBREW_CELLAR: /home/jeefy/.homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 3.1.4 => /usr/bin/ruby
...
📦[jeefy@bluefin ~]$ brew ls
go
📦[jeefy@bluefin ~]$
```

In #745 I add a on-start script just for the DX Bluefin variant, and I'd suggest putting another on-start script in to handle this.

**Comment by jeefy** [comment]
That's another decent approach! My one nit on that is it's (essentially) double-mounting the same folder. If we had to trick `brew`, that's the approach I'd go, but this is something we can configure instead.

**Comment by m2Giles** [comment]
I've been trying to use the brew.env and it seems to pull in a ton of additional packages compared to using the default /home/linuxbrew/.linuxbrew. Additionally, it wants to compile basically everything locally as well. This also seems to fail quite a bit. This was a pretty off experience for me and I think its due to the fact that we are missing most of the brew preinstalled scripts /home/linuxbrew/.linuxbrew.

Everything seems to be in the Cellar. Having just that be linked into the /home/linuxbrew/.linuxbrew will have every package tracked. But they are unlinked when recreating the container. Manually relinking them sorta works, but somethings will require a reinstall (but it's already on disk so it's relatively fast).

But basically, on container enter. Make symlink between $HOME/.homebrew/Cellar and /home/linuxbrew/.linuxbrew. Relink if necessary. Reinstall if necessary. The making a symlink can be done from bash_profile or whatnot. The relink could have a convenience script on the container. The reinstall I have no idea how to catch.

**Comment by m2Giles** [comment]
This is now complete and works with no additional arguments during container creation.
