### ISSUE TITLE
Rework `just update` to be a flex move

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#781]
I realized why I don't like the echoless `just update` with ublue-update. I'm either in 2 modes when I'm using my computer. Automatic, or stick shift. Sometimes I just have to do it the old fashioned way, but of course the automatic is better in every metric for everyday driving. 

I propose adding [topgrade-rs](https://github.com/topgrade-rs/topgrade) to the base bluefin image and then changing `just update` to handle that. But in a way that lets us keep ublue-update because we need that for the transparent rebase to the signed image still. 

So when we want to remember what it was like to do all this stuff by hand we can use it as our nice fidget spinner. Plus it finds lots of stuff, I think it'd be an improvement and another neofetch-like thing people could show off.

**Comment by kylerankin** [comment]
I like the idea of having a tool that lets you trigger the automatic task, but in a way where you can observe (and optionally approve) each step. This is useful for debugging, and also useful whenever you want to confirm that the automated task that happens in the background is truly doing what you expected it to do.

The best automation triggers a series of well-understood, previously-manual steps, but sometimes you do want to step through that automation step-by-step and get better debugging output on what it think it did. I can foresee some day where the automatic bluefin upgrade process silently fails due to some bug, and this sort of feature might help detect/debug that faster.

**Comment by castrojo** [comment]
Alright let's see how it feels, added the binary, we'll leave the `just update` unchanged and see it handles.

**Comment by ethanjli** [comment]
Looks I'm late to the discussion, but I'm excited about the proposed change! When I run `just update`, the sudo prompt always asks me to scan my fingerprint on my laptop's fingerprint reader - but I'm always concerned that the fingerprint scan silently failed, because echoless `just update` gives me no feedback about whether my fingerprint reader is still waiting for me to get a successful scan or whether the command has already started to do work. Having an alternative command which prints some output would confirm to me that my computer is indeed trying to do the update steps.

**Comment by castrojo** [comment]
The close as automatic, let's reopen to get feedback. Command is `topgrade` on the host.

**Comment by EyeCantCU** [comment]
After having looked over tograde, I think this is a fantastic idea. More verbosity during manual updates is a welcome change. Would also be nice to carry over to Bazzite as well

**Comment by andrewbaker-uk** [comment]
Just moved to Bluefin and I'm actually impressed by the detail topgrade gives you :)

**Comment by castrojo** [comment]
```
toolbx failed: 
   0: Command failed: `/usr/bin/toolbox run -c boxkit env 'TOPGRADE_PREFIX='\''Toolbx boxkit'\''' /run/host/usr/bin/topgrade --only system --no-self-update --skip-notify`
   1: `/usr/bin/toolbox` failed: exit status: 1

Location:
   src/steps/toolbx.rs:62
Retry? (y)es/(N)o/(s)hell/(q)uit
```

This is weird, I don't use toolboxes so maybe it's conflicting with my distroboxes?

**Comment by p5** [comment]
> ```
> toolbx failed: 
>    0: Command failed: `/usr/bin/toolbox run -c boxkit env 'TOPGRADE_PREFIX='\''Toolbx boxkit'\''' /run/host/usr/bin/topgrade --only system --no-self-update --skip-notify`
>    1: `/usr/bin/toolbox` failed: exit status: 1
> 
> Location:
>    src/steps/toolbx.rs:62
> Retry? (y)es/(N)o/(s)hell/(q)uit
> ```
> 
> This is weird, I don't use toolboxes so maybe it's conflicting with my distroboxes? 
> 

Isn't this what Brian mentioned yesterday - topgrade gets confused with Distrobox and Toolbox?

**Comment by FlyinPancake** [comment]
The problem stems from toolbx recognizing distrobox containers as toolbx containers

You can check this out with running `toolbox list` it will show your distroboxes.

**Comment by m2Giles** [comment]
I need to check how distrobox tags it's own containers to see if we can add to topgrade a check that compares if it's toolbx or actually a distrobox. This might be a welcome patch since I don't think it's unheard or to have both toolbox and distrobox installed.

I also currently have some reservations about the upgrade being applied live and wonder if we can set a flag or option.

**Comment by castrojo** [comment]
Yeah apply live is an odd thing to have by default, maybe we can change their mind?

**Comment by gerblesh** [comment]
@KyleGospo I 100% agree, it would also make `ublue-update` much easier to maintain, a couple things that we might want to consider though:
1. dbus notifications (and a toggle to turn them off)
2. system checks (battery, wifi/internet, RAM usage, CPU, possibly GPU)
3. multi-user updates (running user updates for active users as well as root)
I think this is definitely the way to go though, and i'm sure most of these could probably be solved by making scripts to be executed by topgrade, and (possibly) having a script to do system checks before running topgrade

**Comment by KyleGospo** [comment]
#3 should be working today
