### ISSUE TITLE
libfprint

### ISSUE THREAD

**Issue by juliusm254** [ublue-os/bluefin#881]
### Describe the package

I'd like to request the package `libfprint` because I have a DELL XPS 9500 and I cant use my fingerprint reader.

Thanks

### Image

All Images

**Comment by bsherman** [comment]
`libfprint` is already included in Bluefin (and Silverblue, in general). The problem is that there is no open driver for the fingerprint reader on that machine. This is a common problem with Dell and others not specifically built with Linux support in mind.

The XPS 9500 is on a list of known unsupported models for the Goodix driver https://gitlab.freedesktop.org/libfprint/wiki/-/wikis/Unsupported%20Devices

So there's no way for us to make this happen.

**Comment by castrojo** [comment]
Bummer, thanks for investigating this!
