### ISSUE TITLE
Connect vscode to distroboxes via podman?

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#883]
The gift that keeps on giving! Luca thinks we can use this:

https://github.com/89luca89/distrobox/blob/main/docs/posts/integrate_vscode_distrobox.md#third-step-podman-wrapper

to connect podman to distroboxes, that way people can have their cake and eat it too if they just _have_ to have their distroboxes connected to vscode. We could toss this wrapper on the image somewhere and then have people opt-in or `ujust` switch to this perhaps as an option?

Leaving this open for discussion and if someone wants to pick it up.

**Comment by castrojo** [comment]
Ok this is on the host now via another PR? I think we need to add the remote vscode extension to the profile (I can work on this), anything else?

**Comment by 89luca89** [comment]
Yes needs the remote extension, and a setting to use this instead of docker

Which I wouldn't do by default I guess

**Comment by castrojo** [comment]
I added the extension: https://github.com/ublue-os/bluefin/pull/888/files

I'll post on the forum and get feedback before we close this.

**Comment by HikariKnight** [comment]
> Ok this is on the host now via another PR. I think we need to add the remote vscode extension to the profile (I can work on this), anything else?

that script is on the host and you point the extension to it instead of `docker`, thats it 😃

**Comment by m2Giles** [comment]
Can confirm that this works with distrobox. Toolbox did not work with a standard toolbox but worked with a quadlet based one (sorta still connected as root)

Oddities I noticed, since I had setup dotfiles with the dev-containers extension, it pulled in my dotfiles deploy script unexpectedly.

Additionally, it does not fully set-up everything for distrobox and toolbox. You will need to manually setup some environment variables to get distrobox-host-exec to work.

This worked best with distroboxes with their own $HOME.

I like that this is on disk. I'm unsure I would have this be the default experience.

 It should be easy to use jq to add the necessary keys to the config.json to automate enabling and disabling this using a just command.

**Comment by 89luca89** [comment]
>Additionally, it does not fully set-up everything for distrobox and toolbox. You will need to manually setup some environment variables to get distrobox-host-exec to work.
This worked best with distroboxes with their own $HOME.

Yes because it does not actually do a `distrobox enter`
It would be better if we manage to do it with distrobox enter, but I didn't manage to do it

Maybe needs more work/testing
