### ISSUE TITLE
boxbuddy's default terminal not set to ptyxis

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#974]
ptyxis is an option, it's just not the default, probably just need to set a dconf key.

**Comment by fiftydinar** [comment]
This is probably because skel is only copying files to $HOME when new user is created.
So when you use an existing system, you won't get that functionality automatically, while new users will.

I believe that Bazzite handles this scenario in their "bazzite-user-setup" service, where they just copy that file from skel to final directory, so it updates on boot.

**Comment by m2Giles** [comment]
Part of this was also held back by 38 not having access to ptyxis.
